language: go

go:
  - 1.3
  - 1.4

script:
  - make test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/45ca6f08e39dbe1809a3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false